// Unified sentiment + photo input verification. Replies are stand-ins, not AI accuracy tests.
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const BASE = process.env.BASE_URL || 'http://localhost:3100';
const OUT = process.env.OUT || path.join(process.cwd(), 'photo-chat-e2e-out');
fs.mkdirSync(OUT, { recursive: true });
let checks = 0;
const check = (ok, name) => { assert.ok(ok, name); checks++; console.log('PASS', name); };
const sst2 = 'distilbert/distilbert-base-uncased-finetuned-sst-2-english';
const finbert = 'ProsusAI/finbert';
const visible = 'Terrible service. The delivery arrived broken.';
const local = { id: 'local-vision', vision: true, cloud: false };
const cloud = { id: 'gemma4:31b-cloud', vision: true, cloud: true };
const textOnly = { id: 'gemma3:1b', vision: false, cloud: false };
const modelInfo = (id, name) => ({ id, name, domain: 'Topic', description: 'Test model', languages: 'English', parameters: 'tiny', architecture: 'BERT', labels: ['negative', 'positive'], revision: 'test', default: id === sst2, status: 'ready', error: null });
const prediction = (model, text) => ({ model: model || sst2, device: 'cpu', latency_ms: 12, label: 'negative', score: .9, probs: [{ label: 'negative', score: .9, logit: 1 }, { label: 'positive', score: .1, logit: 0 }], tokens: ['terrible', 'service'], num_tokens: 8, truncated: false, attributions: [{ text, weight: -.8 }] });

(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    let listing = { models: [local, textOnly, cloud], default_vision: local.id, image_limits: { per_message: 5, per_request: 20, max_bytes: 10 * 1024 * 1024 } };
    let failure = false;
    const photoRequests = [], textRequests = [];
    await page.route('**/api/models', route => route.fulfill({ json: { models: [modelInfo(sst2, 'DistilBERT SST-2'), modelInfo(finbert, 'FinBERT')], default_model: sst2, device: 'cpu', limits: { max_length: 512, max_text_chars: 5000, max_batch_items: 1000, batch_size: 32, explain_steps: 16, low_confidence: .6 } } }));
    await page.route('**/api/photo-models', route => route.fulfill({ json: listing }));
    await page.route('**/api/predict', route => { const body = route.request().postDataJSON(); textRequests.push(body); return route.fulfill({ json: prediction(body.model, body.text) }); });
    await page.route('**/api/predict/photos', route => {
      const body = route.request().postDataJSON(); photoRequests.push(body);
      if (failure) return route.fulfill({ status: 503, json: { detail: 'The photo reader failed. Please try again.' } });
      const answer = body.task === 'question' ? 'The product looks damaged.' : visible;
      const analyzed = body.task === 'question' ? answer : [body.text, answer].filter(Boolean).join('\n\n');
      return route.fulfill({ json: { ...prediction(body.model, analyzed), analyzed_text: analyzed, photo_text: answer, photo_model: body.photo_model || local.id, photo_task: body.task, photo_latency_ms: 20 } });
    });
    await page.goto(BASE);
    await page.getByRole('combobox', { name: 'Model', exact: true }).waitFor();
    check(await page.getByRole('tab', { name: 'Photos', exact: true }).count() === 0, 'no separate Photos tab');
    check(await page.getByRole('tab').count() === 3, 'original three views preserved');
    await page.getByLabel('Text to analyze', { exact: true }).fill('The service was terrible.');
    await page.getByRole('button', { name: /^Analyze/ }).click();
    await page.getByText('Class probabilities', { exact: true }).waitFor();
    check(textRequests.length === 1 && photoRequests.length === 0, 'text-only workflow unchanged');
    await page.getByRole('button', { name: 'New analysis', exact: true }).click();
    await page.getByRole('button', { name: 'Add photos', exact: true }).click();
    check(await page.getByRole('menuitem', { name: /Take a photo/ }).isVisible(), 'camera option remains');
    await page.keyboard.press('Escape');
    const png = await page.evaluate(() => { const canvas = document.createElement('canvas'); canvas.width = 3000; canvas.height = 1500; canvas.getContext('2d').fillRect(0, 0, 3000, 1500); return canvas.toDataURL('image/png').split(',')[1]; });
    const photo = { name: 'review.png', mimeType: 'image/png', buffer: Buffer.from(png, 'base64') };
    await page.getByTestId('photo-input').setInputFiles(photo);
    await page.getByRole('button', { name: 'View review.png' }).waitFor();
    await page.waitForFunction(() => ![...document.querySelectorAll('button')].find(b => b.textContent.startsWith('Analyze'))?.disabled);
    await page.getByText('2048px', { exact: true }).waitFor();
    check(true, 'photo resize retained');
    check(await page.getByRole('combobox', { name: 'Photo reader model' }).isVisible(), 'photo controls appear inside input card');
    await page.getByRole('button', { name: /^Analyze/ }).click();
    await page.getByText('Text read from photos', { exact: true }).waitFor();
    check(photoRequests[0].model === sst2 && photoRequests[0].images.length === 1, 'photo sent to selected sentiment pipeline');
    check(photoRequests[0].photo_model === null, 'Auto uses server local preference');
    check(await page.getByText('Class probabilities', { exact: true }).isVisible(), 'photo shows ordinary class probabilities');
    check(await page.getByRole('heading', { name: 'Word influence', exact: true }).isVisible(), 'photo shows ordinary word explanations');
    check(await page.getByRole('navigation', { name: 'Recent analyses' }).getByRole('button').count() === 2, 'photo result saved in same history');
    const rescored = page.waitForResponse('**/api/predict');
    await page.getByRole('combobox', { name: 'Model', exact: true }).click();
    await page.getByRole('option', { name: /FinBERT/ }).click();
    await page.waitForFunction(() => document.querySelector('[data-slot="card"]') && document.body.textContent.includes('Text read from photos'));
    await rescored;
    check(photoRequests.length === 1 && textRequests.at(-1).model === finbert && textRequests.at(-1).text === visible, 'model switch rescores existing photo text without resending photo');
    await page.getByRole('button', { name: 'Clear', exact: true }).last().click();
    await page.getByText('Source photos', { exact: true }).click();
    await page.getByRole('button', { name: 'View review.png' }).click();
    check(await page.getByRole('dialog').locator('img').getAttribute('src').then(src => src.startsWith('blob:')), 'removing composer photo preserves result photo');
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'New analysis', exact: true }).click();
    await page.getByRole('navigation', { name: 'Recent analyses' }).getByRole('button').first().click();
    await page.getByText('Text read from photos', { exact: true }).waitFor();
    check(photoRequests.length === 1, 'history reopens photo text without new vision request');
    await page.reload();
    await page.getByRole('navigation', { name: 'Recent analyses' }).getByRole('button').first().click();
    await page.getByText('Text read from photos', { exact: true }).waitFor();
    check(true, 'photo provenance survives refresh');
    await page.getByRole('button', { name: 'New analysis', exact: true }).click();
    await page.getByTestId('photo-input').setInputFiles(photo);
    await page.getByRole('button', { name: 'View review.png' }).waitFor();
    const choose = async (label, option) => { await page.getByRole('combobox', { name: label, exact: true }).click(); await page.getByRole('option', { name: option, exact: true }).click(); };
    await choose('Photo reader model', 'gemma3:1b · Local · Text only');
    check(await page.getByRole('button', { name: /^Analyze/ }).isDisabled(), 'text-only photo reader blocks photo analysis');
    await page.getByRole('button', { name: 'Use local-vision' }).click();
    await choose('Photo reader model', 'gemma4:31b-cloud · Cloud · Sees images');
    check(await page.getByText(/Photos are sent to Ollama Cloud/).isVisible(), 'cloud destination disclosed');
    await choose('Photo task', 'Ask a question');
    check(await page.getByRole('button', { name: /^Analyze/ }).isDisabled(), 'question task requires question');
    await page.getByLabel('Text to analyze', { exact: true }).fill('Is it damaged?');
    await page.getByRole('button', { name: /^Analyze/ }).click();
    await page.getByText('Photo answer', { exact: true }).waitFor();
    check(photoRequests.at(-1).task === 'question' && photoRequests.at(-1).photo_model === cloud.id, 'question and explicit cloud selection passed');
    await page.getByLabel('Text to analyze', { exact: true }).fill('What should I inspect?');
    await page.getByRole('button', { name: /^Analyze/ }).click();
    await page.getByText('Photo answer', { exact: true }).waitFor();
    check(photoRequests.at(-1).context.length === 2, 'follow-up question keeps photo context');
    failure = true;
    await page.getByRole('button', { name: /^Analyze/ }).click();
    await page.getByRole('alert').filter({ hasText: 'The photo reader failed' }).waitFor();
    check(true, 'photo failure visible in original result card');
    failure = false;
    await page.getByRole('button', { name: 'Try again', exact: true }).click();
    await page.getByText('Photo answer', { exact: true }).waitFor();
    check(true, 'retry recovers');
    await page.screenshot({ path: path.join(OUT, 'unified-light.png') });
    await page.getByRole('button', { name: 'Switch between light and dark' }).click();
    await page.screenshot({ path: path.join(OUT, 'unified-dark.png') });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: /^Analyze/ }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: path.join(OUT, 'unified-phone.png') });
    console.log(await page.evaluate(() => [...document.querySelectorAll('main *')].filter(e => e.getBoundingClientRect().right > innerWidth).map(e => ({tag: e.tagName, width: e.getBoundingClientRect().width, text: e.textContent.slice(0,60), class: e.className})).slice(0,12)));
    check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.querySelector('main').scrollWidth <= document.querySelector('main').clientWidth), '390px layout has no horizontal scroll');
    check(errors.length === 0, `no browser runtime errors: ${errors.join('; ')}`);
    console.log(`${checks} unified browser checks passed. Screenshots: ${OUT}`);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
